#!/usr/bin/env ruby
#
# rmnupdate v1.0 - create/update symlinks
# Copyright (c) 2014 Ross Nelson
# Licensed under the zlib license
#

BASEDIR = '/rmnbin'
INSTDIR = '/usr/local'
DIRECTORIES = [ 'bin', 'sbin' ]

# Only run as root
if 0 != Process.uid
	puts 'error: must run rmnupdate as root'
	exit false
end

# Make sure we have the correct tree
DIRECTORIES.each do |directory|
  command = "mkdir -p #{File.join INSTDIR, directory}"
  system command
end

DIRECTORIES.each do |suffix|
  source_directory = File.join BASEDIR, suffix
  destination_directory = File.join INSTDIR, suffix
  
  Dir.entries(source_directory).each do |file|
    if '.' != file && '..' != file
      source_file = File.join source_directory, file
      destination_file = File.join destination_directory, file
      
      # Remove the current link
      if File.exists? destination_file
        command = "rm #{destination_file}"
        system command
      end

      # Create a new link
      command = "ln -s #{source_file} #{destination_file}"
      system command
    end
  end
end
